version: '3.9'

services:
  web:
    build: .
    command: gunicorn task_manager.wsgi:application --bind 0.0.0.0:8000 --workers 4
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      DJANGO_SETTINGS_MODULE: "task_manager.settings"

  test:
    build: .
    command: pytest -v task_manager/  --disable-warnings
    volumes:
      - .:/app
    environment:
      DJANGO_SETTINGS_MODULE: "task_manager.settings"
